# Generated by Django 5.2 on 2025-05-22 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="products_images/"
            ),
            preserve_default=False,
        ),
    ]
