# Generated by Django 5.2 on 2025-05-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.JSONField(default=list),
        ),
    ]
